### ISSUE TITLE
correct path in Make_TFRecord_Class for different call #2

### ISSUE THREAD

**Issue by guatavita** [brianmanderson/Base_Deeplearning_Code#3]
Actually my merge does nothing cause you need to modify a submodules and I have no write access.

Can you take the time to do that for future clone?

In:

**Base_Deeplearning_Code/Make_Single_Images/Make_TFRecord_Class.py**

Need to add:

`from .Image_Processors_Module.src.Processors.TFRecordWriter import *`

_Originally posted by @guatavita in https://github.com/brianmanderson/Base_Deeplearning_Code/issues/2#issuecomment-867738870_

**Comment by brianmanderson** [comment]
Updated, thank you!
